"""PDF export utility — generates a downloadable emergency plan report.

Uses fpdf2 for PDF generation. Gracefully falls back if the library is
not installed.
"""

from typing import Any


def generate_pdf(plan: dict, trace: list[dict]) -> bytes:
    """Generate a PDF report of the emergency plan.

    Args:
        plan: The final EmergencyPlan dict from the Synthesizer.
        trace: The list of trace events from the pipeline.

    Returns:
        PDF file contents as bytes.
    """
    try:
        return _generate_pdf_internal(plan, trace)
    except ImportError:
        return _generate_text_fallback(plan, trace)
    except Exception:
        return _generate_text_fallback(plan, trace)


def _generate_pdf_internal(plan: dict, trace: list[dict]) -> bytes:
    """Internal PDF generation using fpdf2."""
    from fpdf import FPDF
    import io

    pdf = FPDF()
    pdf.add_page()

    # ── Header ──
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 12, "ResQ AI - Emergency Action Plan", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Priority
    priority = plan.get("priority_level", "moderate").upper()
    severity = plan.get("severity_score", 3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Priority: {priority}  |  Severity: {severity}/5", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Disclaimers ──
    for disclaimer in plan.get("disclaimers", []):
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(146, 64, 14)
        pdf.set_fill_color(254, 243, 199)
        pdf.multi_cell(0, 5, f"Disclaimer: {disclaimer}", fill=True)
        pdf.ln(2)

    # ── Immediate Safety Steps ──
    safety = plan.get("immediate_safety_steps", [])
    if safety:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 8, "Immediate Safety Steps", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for i, step in enumerate(safety, 1):
            pdf.multi_cell(0, 6, f"{i}. {step}")
        pdf.ln(3)

    # ── Medical Advice ──
    medical = plan.get("medical_advice", [])
    if medical:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Medical Advice", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for i, advice in enumerate(medical, 1):
            pdf.multi_cell(0, 6, f"{i}. {advice}")
        pdf.ln(3)

    # ── Supply Checklist ──
    supplies = plan.get("supply_checklist", [])
    if supplies:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Supply Checklist", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        categories: dict[str, list] = {}
        for item in supplies:
            cat = item.get("category", "other")
            categories.setdefault(cat, []).append(item.get("content", item.get("name", "")))
        for cat, items in categories.items():
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, cat.capitalize(), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            for item_text in items:
                pdf.cell(0, 5, f"  - {item_text}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # ── Communication Drafts ──
    comms = plan.get("communication_drafts", {})
    if comms:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Communication Drafts", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for label, draft in comms.items():
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, label.replace("_", " ").title(), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, draft)
            pdf.ln(2)

    # ── Recovery Checklist ──
    recovery = plan.get("recovery_checklist", [])
    if recovery:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Recovery Checklist", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for i, step in enumerate(recovery, 1):
            pdf.multi_cell(0, 6, f"{i}. {step}")

    # ── Footer ──
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by ResQ AI - Multi-Agent Disaster Response System", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "This is AI-generated guidance. Always follow official emergency services instructions.", new_x="LMARGIN", new_y="NEXT")

    return pdf.output().encode("latin-1", errors="replace")


def _generate_text_fallback(plan: dict, trace: list[dict]) -> bytes:
    """Fallback plain-text report when fpdf2 is not available."""
    lines: list[str] = []
    lines.append("=" * 50)
    lines.append("RESQ AI - EMERGENCY ACTION PLAN")
    lines.append("=" * 50)
    lines.append("")

    priority = plan.get("priority_level", "moderate").upper()
    severity = plan.get("severity_score", 3)
    lines.append(f"Priority: {priority}  |  Severity: {severity}/5")
    lines.append("")

    for disclaimer in plan.get("disclaimers", []):
        lines.append(f"[DISCLAIMER] {disclaimer}")
        lines.append("")

    safety = plan.get("immediate_safety_steps", [])
    if safety:
        lines.append("IMMEDIATE SAFETY STEPS:")
        for i, step in enumerate(safety, 1):
            lines.append(f"  {i}. {step}")
        lines.append("")

    medical = plan.get("medical_advice", [])
    if medical:
        lines.append("MEDICAL ADVICE:")
        for i, advice in enumerate(medical, 1):
            lines.append(f"  {i}. {advice}")
        lines.append("")

    comms = plan.get("communication_drafts", {})
    if comms:
        lines.append("COMMUNICATION DRAFTS:")
        for label, draft in comms.items():
            lines.append(f"  {label.replace('_', ' ').title()}:")
            lines.append(f"    {draft}")
        lines.append("")

    recovery = plan.get("recovery_checklist", [])
    if recovery:
        lines.append("RECOVERY CHECKLIST:")
        for i, step in enumerate(recovery, 1):
            lines.append(f"  {i}. {step}")

    lines.append("")
    lines.append("-" * 50)
    lines.append("Generated by ResQ AI - Multi-Agent Disaster Response System")
    lines.append("AI-generated guidance. Follow official emergency services instructions.")

    return "\n".join(lines).encode("utf-8")
